guacamole: Drop `proudct.prop`
For various reasons:
 - GBoard properties are already specified source-side, and that just generates
   conflicts between the two.
    * Fixes:
    error: found duplicate sysprop assignments:
    ro.com.google.ime.kb_pad_land_r=14
    ro.com.google.ime.kb_pad_land_r=64
    error: found duplicate sysprop assignments:
    ro.com.google.ime.kb_pad_land_l=14
    ro.com.google.ime.kb_pad_land_l=64
    error: found duplicate sysprop assignments:
    ro.com.google.ime.kb_pad_port_r=7
    ro.com.google.ime.kb_pad_port_r=4
    error: found duplicate sysprop assignments:
    ro.com.google.ime.kb_pad_port_l=7
    ro.com.google.ime.kb_pad_port_l=4
 - We do not use Baidu keyboard. Who the hell decided it was a good idea to add that?